feat: add chunkFilter option
webpack-contrib/terser-webpack-plugin pull request #362
Opened 2020-11-27 00:59 UTC by WearyMonkey

This PR contains a:

- [ ] **bugfix**
- [x ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

We do not tag our vendor assets with a `.vendor.js` postfix, so when the terser plugin runs the `test|include|option` it only sees the generated hash name and has no way to filter out the vendor chunks.

Conditionally naming our assets just so they can be filtered in the plugin adds complexity to our build configuration, and leaks unnecessary information.

By re-adding the `chunkFilter` option, we can filter the assets on their non-hashed non-public chunk name.

Thanks!

### Breaking Changes

None

### Additional Info

https://github.com/webpack-contrib/terser-webpack-plugin/issues/361

2020-11-27 11:41 UTC, alexander-akait requested changes
Even you want to filter chunks using function, it is invalid solution, we don't compress 'chunks', we compress assets, this is why the option was removed, not all chunks hashed, not all chunks can have non public name

2020-11-27 11:53 UTC, WearyMonkey commented
> we don't compress 'chunks', we compress assets,

Sure, I am filtering the assets by the chunk they are assigned to. I can rename the function to `filterAssetByChunk`.

> it's not safe

Can you explain what's not safe? Is it because not all assets are assigned to a chunk?

Or is there any other solution that doesn't involve renaming the assets?

2020-11-27 11:58 UTC, alexander-akait commented
@WearyMonkey 

> Sure, I am filtering the assets by the chunk they are assigned to. I can rename the function to filterAssetByChunk.
> Can you explain what's not safe? Is it because not all assets are assigned to a chunk?

Unfortunately, this works here, but in reality it may not work, because previously plugin can merge/change/etc sources of assets, and then it is simply not possible to detect the real original name

> Or is there any other solution that doesn't involve renaming the assets?

In theory yes, we can keep some additional information (like original name) in assets info and allow developers to use `Function` in `test`/`include`/`exclude` and provide this asset info in function, but it is require improvements on webpack side (right now we do the same for assets modules and some plugins, but not for JS/CSS chunks)

2020-11-30 22:29 UTC, WearyMonkey commented
Thanks for your reply! That's reasonable.

2020-11-30 22:35 UTC, closed without merging